#name: Install Software packages
---
- hosts: app
#  roles: app
  become: true
  vars:
    package: nginx
    package: nodejs
    package: npm
    package: git
    package: python
  tasks:
  #  name: Install “{{ item.name }}”on ubuntu
  #  tasks:
  - name: install system updates for ubuntu systems
    apt: upgrade=dist
    name: update cache
    apt: update_cache=yes
#      when: ansible_distribution == "Ubuntu"
    name: Install Package
    apt: name={{ package }} state=latest
#      with_items:
  #    - "{{ package }}"
#apt:
# name: “{{ item.name }}”
# state: present
#When: item.required == True
#  loop: “{{ packages }}”
