
- name: install system updates for ubuntu systems
  apt: upgrade=dist update_cache=yes
  when: ansible_distribution == "Ubuntu"
  ---
 - name: Install Software packages
    hosts: all
    vars:
          packages:
    • name: nginx
required: True
    name: nodejs
required: True
    name: pm2
required: True

  tasks:
    • name: Install “{{ item.name }}”on ubuntu
apt:
 name: “{{ item.name }}”
 state: present
When: item.required == True
loop: “{{ packages }}”
